# Generated by Django 3.1 on 2020-09-08 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20200830_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='total_questions',
        ),
    ]
